export const DEMO_DATA = {
  demo1: {
    scan_id: 'demo-1',
    timestamp: new Date().toISOString(),
    summary: { total_files:1, total_vulnerabilities:7, high_risk:4, medium_risk:2, low_risk:1, scan_duration_ms:312, vulnerability_types:{} },
    results: [
      { file:'vulnerable_app.c', line:12, vulnerability:'Unsafe API: gets()', risk_score:0.95, severity:'CRITICAL',
        explanation:'gets() reads input with no bounds checking, allowing attackers to write beyond the buffer boundary. It was removed from the C11 standard entirely.',
        fix:'Replace gets(buf) with fgets(buf, sizeof(buf), stdin) to enforce a maximum read length.',
        code_snippet:'10: char buffer[64];\n11: printf("Enter name: ");\n12: gets(buffer);\n13: printf("Hello, %s!\\n", buffer);' },
      { file:'vulnerable_app.c', line:23, vulnerability:'Command Injection Risk: system()', risk_score:0.91, severity:'CRITICAL',
        explanation:'system() passes the argument string to the shell interpreter. Any user-controlled portion enables arbitrary command injection and privilege escalation.',
        fix:'Use execve() with explicit argument arrays instead of system(). Validate and sanitize all inputs before use.',
        code_snippet:'21: void run_command(char *user_input) {\n22:   char cmd[256];\n23:   system(user_input);\n24: }' },
      { file:'vulnerable_app.c', line:55, vulnerability:'Format String Vulnerability', risk_score:0.90, severity:'CRITICAL',
        explanation:'Passing a user-controlled variable directly as the format argument to printf() enables format string attacks — reading stack memory or writing arbitrary values.',
        fix:'Always use printf("%s", user_input) — never printf(user_input).',
        code_snippet:'53: void display_message(char *msg) {\n54:   // BUG: direct format arg\n55:   printf(msg);\n56: }' },
      { file:'vulnerable_app.c', line:38, vulnerability:'Unsafe API: strcpy()', risk_score:0.88, severity:'HIGH',
        explanation:'strcpy() copies without checking the destination buffer size. If the source string exceeds the destination, a stack or heap buffer overflow occurs.',
        fix:'Replace strcpy(dst, src) with strncpy(dst, src, sizeof(dst)-1); dst[sizeof(dst)-1] = \'\\0\';',
        code_snippet:'36: void set_username(char *name) {\n37:   char username[32];\n38:   strcpy(username, name);\n39: }' },
      { file:'vulnerable_app.c', line:79, vulnerability:'Unsafe API: scanf() with %s', risk_score:0.85, severity:'HIGH',
        explanation:'%s in scanf() reads an unbounded number of characters. Attacker-controlled input can overflow the target buffer on the stack.',
        fix:'Use scanf("%15s", password) with an explicit width bound, or prefer fgets() for line input.',
        code_snippet:'77: char password[16];\n78: printf("Password: ");\n79: scanf("%s", password);\n80: validate(password);' },
      { file:'vulnerable_app.c', line:67, vulnerability:'Unsafe API: sprintf()', risk_score:0.83, severity:'HIGH',
        explanation:'sprintf() writes to a buffer without size limits. If the formatted output exceeds the buffer, adjacent memory is overwritten.',
        fix:'Replace sprintf(query, fmt, arg) with snprintf(query, sizeof(query), fmt, arg).',
        code_snippet:'65: char query[128];\n66: // SQL construction — dangerous\n67: sprintf(query, "SELECT * FROM users WHERE name=\'%s\'", input);\n68: db_exec(query);' },
      { file:'vulnerable_app.c', line:91, vulnerability:'Buffer Declaration (Review Required)', risk_score:0.32, severity:'LOW',
        explanation:'Fixed-size char arrays are frequent overflow targets. Ensure every write to these buffers is explicitly bounds-checked.',
        fix:'Audit all writes to these buffers and add size guards before each one.',
        code_snippet:'89: // Global buffers\n90: static char log_buf[512];\n91: char error_msg[256];\n92: int error_code;' },
    ]
  },

  demo2: {
    scan_id: 'demo-2',
    timestamp: new Date().toISOString(),
    summary: { total_files:1, total_vulnerabilities:3, high_risk:2, medium_risk:1, low_risk:0, scan_duration_ms:187, vulnerability_types:{} },
    results: [
      { file:'string_utils.cpp', line:52, vulnerability:'Memory: Potential Double Free', risk_score:0.82, severity:'HIGH',
        explanation:'Freeing a pointer twice corrupts the heap allocator\'s internal state, potentially enabling use-after-free exploitation and arbitrary code execution.',
        fix:'Set pointer to NULL immediately after free: free(ptr); ptr = NULL; Add a null guard before every free call.',
        code_snippet:'50: void cleanup(char* p, char* q) {\n51:   if (p) free(p);\n52:   if (q) free(q);\n53:   free(p); // BUG: double free on p\n54: }' },
      { file:'string_utils.cpp', line:18, vulnerability:'Unsafe API: strcat()', risk_score:0.80, severity:'HIGH',
        explanation:'strcat() appends to the destination without checking remaining capacity. Repeated appends can overflow the destination buffer.',
        fix:'Replace strcat(path, sub) with strncat(path, sub, sizeof(path)-strlen(path)-1).',
        code_snippet:'16: void buildPath(char* path, const char* sub) {\n17:   // No space check!\n18:   strcat(path, "/");\n19:   strcat(path, sub);\n20: }' },
      { file:'string_utils.cpp', line:34, vulnerability:'Memory: Unchecked malloc()', risk_score:0.57, severity:'MEDIUM',
        explanation:'malloc() returns NULL when the system cannot satisfy the request. Dereferencing a NULL pointer causes undefined behaviour and crashes.',
        fix:'Always check: char* buf = malloc(sz); if (!buf) { perror("malloc"); return NULL; }',
        code_snippet:'32: char* createBuffer(size_t sz) {\n33:   char* buf;\n34:   buf = (char*)malloc(sz);\n35:   memset(buf, 0, sz); // crash if NULL\n36:   return buf;\n37: }' },
    ]
  },

  demo3: {
    scan_id: 'demo-3',
    timestamp: new Date().toISOString(),
    summary: { total_files:1, total_vulnerabilities:5, high_risk:3, medium_risk:1, low_risk:1, scan_duration_ms:241, vulnerability_types:{} },
    results: [
      { file:'auth_handler.c', line:8, vulnerability:'Unsafe API: gets()', risk_score:0.95, severity:'CRITICAL',
        explanation:'gets() has no length parameter — a malicious user can overwrite the stack beyond the username buffer, enabling return-address hijacking.',
        fix:'Replace gets(c->username) with fgets(c->username, sizeof(c->username), stdin).',
        code_snippet:'6: void read_credentials(Creds *c) {\n7:   printf("Username: ");\n8:   gets(c->username);\n9:   printf("Password: ");\n10:  gets(c->password);' },
      { file:'auth_handler.c', line:27, vulnerability:'Command Injection Risk: system()', risk_score:0.88, severity:'HIGH',
        explanation:'The log message includes unsanitized user input passed to system() via a shell. An attacker can inject shell metacharacters to execute arbitrary commands.',
        fix:'Escape the username or write to the log file directly with fprintf() rather than invoking a shell.',
        code_snippet:'25: int log_login(char *user) {\n26:   char cmd[256];\n27:   sprintf(cmd, "echo \'%s logged in\' >> /var/log/auth.log", user);\n28:   system(cmd);\n29: }' },
      { file:'auth_handler.c', line:41, vulnerability:'Unsafe API: strcpy()', risk_score:0.86, severity:'HIGH',
        explanation:'The session token field is 64 bytes but strcpy() enforces no limit. An oversized token from the server can overwrite adjacent struct fields.',
        fix:'Use strncpy(s->token, tok, sizeof(s->token)-1); s->token[sizeof(s->token)-1] = \'\\0\';',
        code_snippet:'39: void store_token(Session *s, char *tok) {\n40:   // token max 64 but no enforcement\n41:   strcpy(s->token, tok);\n42: }' },
      { file:'auth_handler.c', line:58, vulnerability:'Format String Vulnerability', risk_score:0.68, severity:'HIGH',
        explanation:'err_msg may contain format specifiers controlled by the caller. If user-supplied, an attacker can leak memory or write arbitrary values.',
        fix:'Change to printf("%s", err_msg); to treat err_msg as data, not a format string.',
        code_snippet:'56: void show_error(char *err_msg) {\n57:   fprintf(stderr, "Auth error: ");\n58:   printf(err_msg); // BUG: format string\n59: }' },
      { file:'auth_handler.c', line:73, vulnerability:'Buffer Declaration (Review Required)', risk_score:0.30, severity:'LOW',
        explanation:'Fixed-size credential buffers are primary targets for overflow attacks. Each field must be written with strict bounds enforcement.',
        fix:'Ensure every write to username, password, and token uses size-aware functions with sizeof(field) as the bound.',
        code_snippet:'71: typedef struct {\n72:   char username[64];\n73:   char password[32];\n74:   char token[64];\n75: } Creds;' },
    ]
  }
}
